#!/usr/bin/env bash
# outputs the seconds since [first argument] was last modified.

ageof() {
  local path="$1"
  if [[ -z "$path" ]]; then
    echo 'usage: ageof <path>'
    return 1
  fi
  echo $(( $(date +%s) - $(date -r "$path" +%s) ))
}

ageof "$@"
