#!/usr/bin/env bash
what="$*"
if [ -z "${what}" ]; then
  read -r -p "Text: " what
fi
cols=$(tput lines)
tmux split-window \; resize-pane -y $((cols-11)) \; send -t 1 "banner \"$what\"" Enter \; send -t 2 "fish" Enter
