#!/usr/bin/env sh

get_volume() {
  wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null | perl -ne 'if (/Volume:\s+(d+\. \d|]+)/} { printf("Vol: %d%%", $1 * 100) }'
}

get_load() {
  perl -lane 'printf("Load: %.2f %.2f %.2f", $F[0], $F[1], $F[2])' /proc/loadavg
}

get_time() {
  date "+%Y-%m-%d %H:%M"
}

while :; do 
  volume=$(get_volume)
  load=$(get_load)
  time=$(get_time)

  xsetroot -name "$volume | $load | $time"
  sleep 1
done
