#!/bin/sh

if [ -z "$(command -v nvim)" ] ; then
	echo "tmux not found"
fi

rm -rf "$HOME/.tmux.conf"
rm -rf "$HOME/.config/tmux/"
mkdir -p "$HOME/.config/tmux"
ln -sf "$PWD/tmux.conf" "$HOME/.config/tmux/tmux.conf
