#!/usr/bin/env bash

user=cwiggins
channels=cwiggins

echo "generate oauth token here: https://antiscuff.com/oauth"
read -rp "paste token: "

mkdir -p ~/.weechat
fifo=~/.weechat/fifo
log=~/.weechat/log

if [[ ! -p "$fifo" ]]; then
  echo "error: weechat fifo not found at $fifo"
  echo "enable it in weechat with /set fifo.file.path $fifo"
  echo "you may need to enable it with /fifo enable"
  exit 1
fi

cat <<EOF >"$fifo"
*/set logger.file.path "$log"
*/set logger.file.flush_delay 1
*/set weechat.color.chat_bg default
*/set weechat.color.chat_fg 223
*/set weechat.color.chat_nick_self 214
*/set weechat.color.chat_prefix_error 124
*/set weechat.color.chat_prefix_network 66
*/set weechat.color.chat_prefix_action 214
*/set weechat.color.chat_highlight 142
*/set weechat.color.chat_read_marker 214
*/set weechat.color.chat_host 243
*/set weechat.color.chat_buffer 214
*/set weechat.color.separator 243
*/set weechat.look.prefix_join "👋"
*/set weechat.look.prefix_action "🌟"
*/set weechat.look.prefix_error "💢"
*/set weechat.bar.input_items ",input_text"
*/bar hide buflist
*/bar hide title
*/bar hide nicklist
*/set irc.color.nicks ""
*/server add twitch irc.chat.twitch.tv/6667 -ssl
*/set irc.server.twitch.username "$user"
*/set irc.server.twitch.tls off
*/set irc.server.twitch.autoconnect on
*/set irc.server.twitch.autojoin "#${channels//,/,#}"
*/filter add hide_quit irc.* irc_quit *
*/filter add hide_part irc.* irc_part *
*/save
EOF

if test -n "$token"; then
	cat <<EOF >"$fifo"
*/set irc.server.twitch.password "$token"
*/save
EOF
fi

sleep 5
